const en = {
  languageSelector: "English",
  Save: "SAVE",
  OK: "OK",
  Comments: "COMMENTS",
  Submit: "SUBMIT",
  Post: "POST",
  Attendence: "MARK ATTENDED CONTRIBUTORS",
  Change: "CHANGE",
  SaveChanges: "SAVE CHANGES",
  Delete: "DELETE",
  Pending: "PENDING",
  Happening: "HAPPENING",
  Finish: "FINISHED",

  All_Shramadana_Campaigns: "ALL SHRAMADANA CAMPAIGNS",
  Posts: "POSTS",
  HostNewForm: "HOST A NEW SHRAMADANA CAMPAIGN",
  LeaderBoard: "MONTHLY POINTS LEADERBOARD",
  Profile: "PROFILE",
  CampaignsYouHost: "CAMPAIGNS YOU HOST",
  MyPosts: "MY POSTS",
  PointsHistory: "POINTS HISTORY",
  MarkAttendence: "MARK ATTENDENCE",
  CreatePost: "CREATE A POST",

  Location: "LOCATION",
  Place: "PLACE",
  StartTime: "START TIME",
  EndTime: "END TIME",
  Date: "DATE",
  Status: "STATUS",
  Description: "DESCRIPTION",
  Contribute: "CONTRIBUTE",
  CYSHeader: "CONTRIBUTE YOUR SELF",

  FirstName: "FIRST NAME",
  LastName: "LAST NAME",
  ContactNo: "CONTACT NO",
  Contribution: "How Can You Contribute?",
  CYSsnackbar: "Your Contribution Saved",

  Contributors: "CONTRIBUTORS",
  MyContributions: "MY CONTRIBUTIONS",

  CCHsnackbar: "CAMAPAIGN IS SAVED.",

  CampaignsYouHost: "CAMPAIGNS YOU HOST",
  MyPosts: "MY POSTS",
  PointHistory: "POINTS HISTORY",
  SeeMore: "See More",

  CPFsnackbar: "POST IS SAVED",
  ASsnackbar: "ATTENDANCE SAVED",
  SCSsnackbar: "STATUS CHANGED SUCCESSFULLY",
};
const sn = {
  languageSelector: "සිංහල",
  Save: "සුරකින්න",
  OK: "හරි",
  Comments: "අදහස්",
  Submit: "SUBMIT",
  Post: "පලකරන්න",
  Attendence: "සහභාගී වූ දායකයින් සලකුණු කරන්න",
  Change: "වෙනස් කරන්න",
  SaveChanges: "වෙනස්කම් සුරකින්න",
  Delete: "මකන්න",
  Pending: "පොරොත්තුවෙන්",
  Happening: "සිදුවෙමින් පවතී",
  Finish: "අවසන්",

  All_Shramadana_Campaigns: "සියලුම ශ්‍රමදාන ව්‍යාපාර",
  Posts: "පෝස්ට්",
  HostNewForm: "නව ශ්‍රමදාන ව්‍යාපාරයක් පවත්වන්න",
  LeaderBoard: "මාසික ලකුණු ප්‍රමුඛ පුවරුව",
  Profile: "ගිණුම",
  MarkAttendence: "පැමිණීම ලකුණු කරන්න",
  CreatePost: "POST එකක් සාදන්න",

  Location: "ස්ථානය",
  Place: "ස්ථානය",
  StartTime: "ආරම්භක වේලාව",
  EndTime: "අවසන් වේලාව",
  Date: "දිනය",
  Status: "තත්වය",
  Description: "විස්තර",
  Contribute: "දායක වන්න",

  CYSHeader: "ඔබේ දායකත්වය ලබා දෙන්න",
  FirstName: "මුල් නම",
  LastName: "අවසන් නම",
  ContactNo: "දුරකතන අංකය",
  Contribution: "ඔබට දායක විය හැක්කේ කෙසේද?",
  CYSsnackbar: "ඔබගේ දායකත්වය සුරැකිණි",

  Contributors: "දායකයන්",
  MyContributions: "මගේ දායකත්වය",

  CCHsnackbar: "ප්‍රචාරණය සුරකින ලදී.",

  CampaignsYouHost: "ඔබ පවත්වන ව්‍යාපාර",
  MyPosts: "මගේ පෝස්ට්",
  PointHistory: "ලකුණු ඉතිහාසය",
  SeeMore: "තවත් බලන්න",

  CPFsnackbar: "POST සුරැකේ",
  ASsnackbar: "පැමිණීම සුරැකිණි",
  SCSsnackbar: "තත්ත්වය සාර්ථකව වෙනස් විය",
};

export { en, sn };
