
export default Object.freeze({
  LOGIN: "Login",
  REGISTRATION: "Registration",
  SECTIONS: "Sections",
  SECTIONSNAV: "SectionNav",
  HOME: "CampaignsNavigator",
  PROFILE: "Profile",
  SELECTED_CAMPAIGN: "Campaign",
  CONTRIBUTION_FORM: "ContributionForm",
  ALL_CAMPAIGNS: "All Campaign",
  ALL_POSTS: "Posts",
  SELECTED_POST: "Post",
  COMMENTS: "Comments",
  NEW_CAMPAIGN: "Host",
  CAMPAIGNS_YOU_HOST: "HostCampaigns",
  MY_POST: "MyPost",
  POINTS_HISTORY: "PointsHistory",
  SELECTED_MY_CAMPAIGN: "SelectedMyCampaign",
  SELECTED_MY_POSTS: "SelectedMyPosts",
  Attendence: "Attendence",
  CREATE_POST: "CreatePost",
});